config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'customers/index'
  end
  namespace :admins do
    get 'genres/index'
  end
  get 'admins/top'
  get 'home/about'
  get 'customers/show'
  devise_for :customers, skip: :all

  root 'customers/items#index'

  namespace :customers  do
    resources :items, only:[:index,:show,:top]
    delete "cart_items/delete_all" => "cart_items#delete_all"
    get "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    get "customers_my_page" => "customers#show"
    # get "customers_edit" => "customers#edit"
    resource :customers, only:[:edit]
    patch "customers" => "customers#update"
    get "customers_unsubscribe" => "customers#unsubscribe"
    delete "customers_withdraw" => "customers#withdraw"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    resources :addresses, only:[:index,:new,:show,:edit,:update,:create,:destroy]
    resources :orders, only:[:new,:create,:index,:show,:update]
  end

    devise_for :customers, controllers: {sessions: "customers/sessions", registrations: 'customers/registrations', passwords: 'customers/passwords'}


    devise_scope :admin do
    devise_for :admins, controllers: {sessions: "admins/sessions", registrations: 'admins/registrations', passwords: 'admins/passwords'}
    # get "admins/sign_in" => "admins/sessions#new"
    # post "admins/sign_in" => "admins/sessions#create"
    # delete "admins/sign_out" => "admins/sessions#destroy"
  end

 
  namespace :admins  do
    resources :items, only:[:index,:new,:show,:edit,:update,:create]
    resources :genres, only:[:index,:edit,:create,:update]
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:edit,:update]
    resources :addresses
    get "admins" => "orders#count"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:cart_items,  dependent: :destroy
  has_many:orders,  dependent: :destroy
  has_many:addresses,  dependent: :destroy
  acts_as_paranoid
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: ["クレジット","銀行振込"]
    enum status: ["入金待ち","入金完了","製作中","発送準備中","発送済み"]
    validates :name, presence: true,
    length: { minimum: 1,maximum: 50}
    validates :postal_code, presence: true,
    length: { minimum: 1,maximum: 200}
    validates :address, presence: true,
    length: { minimum: 1,maximum: 200}
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
    def index
        @customers = Customer.all
        # if customer.is_deleted = true
        #     customer.is_deleted ='有効'
        # else customer.is_deleted = false
        #     customer.is_deleted ='無効'
        # end
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def show
        @customer = Customer.find(params[:id])
    end

    def update
        @customer = Customer.find(params[:id])
            if @customer.update(customer_params)
            redirect_to admins_customer_path(@customer)
            else
            render "edit"
            end
    end

    private
    def customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
    end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
    def count
        @order = Order.all
    end
    def index
        @orders = Order.all
    end

    def update
        @order = Order.find(params[:id])
        if @order.update(status: order_params[:status].to_i)
            if params[:order][:status] == "1"
                @order.order_details.each do |order_detail|
                    order_detail.making_status = 1
                    order_detail.save
                end
            end
          redirect_to edit_admins_order_detail_path(@order)
        else
          render 'index'
        end
    end

    private
    def order_params
        params.require(:order).permit(:status)
    end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
    before_action :authenticate_customer! 
    def index
        @address = current_customer.addresses.new
        @addresses = Address.where(customer_id: current_customer.id)
        
    end

    def create
        @address = current_customer.addresses.new(address_params)
        @address.customer_id = current_customer.id
        if @address.save
        redirect_to customers_addresses_path(current_customer)
        else
            flash[:notice] = "登録に失敗しました。."
            render "index"
        end
    end

    def new
    end

    def edit
        @address = Address.find(params[:id])
    end

    def show
    end
    
    def update
        @address = Address.find(params[:id])
        if @address.update(address_params)
          redirect_to customers_addresses_path(@address.id)
        else
            @address = current_customer.addresses.new
            @addresses =  current_customer.addresses
          render 'index'
        end
    end
    
    def destroy
        @address = Address.find(params[:id])
        @address.destroy
       redirect_to customers_addresses_path

    end
    private
    def address_params
        params.require(:address).permit(:id,:postal_code, :address, :name)
    end
    end

app/controllers/customers/car_items_controller.rb
class Customers::CarItemsController < ApplicationController
    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end
    
    def upddate
    end

    def destroy
    end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
    before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]
    before_action :authenticate_customer!
    def index
      @cart_items = current_customer.cart_items
      @order = Order.new
    end

    def edit
        @item = Item.find(params[:id])
        @items = Item.all
    end

  def create
      @order = Order.new
      @cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
       if @cart_item.presence
       @cart_item.amount += params[:cart_item][:amount].to_i
        @cart_item.update(amount:@cart_item.amount)
        @cart_item.save
        redirect_to customers_cart_items_path

      elsif   @cart_item = CartItem.new(cart_item_params)
              @cart_item.customer_id = current_customer.id
              @cart_item.save
              @cart_items = CartItem.all
              redirect_to customers_cart_items_path
      else
        @item = Item.find(params[:id])
        render 'customer/items/show'
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      redirect_to customers_cart_items_path(@cart_item.id)
    else
      render 'edit'
    end
  end


    def destroy
     @cart_item = CartItem.find(params[:id])
     @cart_item.destroy
    redirect_to customers_cart_items_path
 end

    def delete_all
      @cart_item_all = current_customer.cart_items
      @cart_item_all.destroy_all
      redirect_to customers_items_path, notice: 'カートが空になりました。'
    end

    private 
    def cart_item_params
      params.require(:cart_item).permit(:amount,:item_id)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true
before_action :authenticate_customer!
class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
   
  
        def show
          @customer = current_customer
        end
        
        def edit
          @customer = current_customer
        end
        def update
          @customer = current_customer
          if @customer.update(customer_params)
            redirect_to customers_customers_my_page_path
          else
            render 'edit'
          end
        end
      
      def unsubscribe
      end
      
      def withdraw
        current_customer.destroy
        redirect_to root_path
      end
        private
        def customer_params
          params.require(:customer).permit(:last_name,:first_name,:first_name_kana,:last_name_kana,:email,:postal_code,:address,:telephone_number)
        end
      end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

    def index
        @items = Item.all
        @genres = Genre.all
    end
    def create

    end

    def new
    end

    def edit
    end

    def show
        @item = Item.find(params[:id])
        @cart_item = CartItem.new
        @genres = Genre.all
    end
    
    def upddate
    end

    def destroy
    end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/order_details_controller.rb
class Customers::OrdersDetailsController < ApplicationController
    before_action :authenticate_customer!
    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end
    
    def upddate
    end

    def destroy
    end
    
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
    before_action :authenticate_customer!
    
    def index
        @orders = Order.where(customer_id:current_customer.id)
        # @cart_items = current_customer.cart_items
        cart_items = CartItem.where(customer_id:current_customer.id)
    end

    def create
         @order = current_customer.orders.new(order_create_params)
        
         @order.status = 0
         if @order.save
            @cart_items = current_customer.cart_items
            @cart_items.each do |cart_item|
               @order_details = @order.order_details.new
               @order_details.item_id = cart_item.item.id
               @order_details.price = cart_item.item.price * $tax
               @order_details.amount = cart_item.amount
               @order_details.making_status = 0
               @order_details.save
            end
             current_customer.cart_items.destroy_all
             redirect_to  customers_orders_complete_path
             else
                render "confirm"
        end

    end 

    def new
        @order = Order.new
    end

    def edit
    end

    def show
        @order = Order.find(params[:id])
        # @order_detail = OrderDetail.find(params[:id])
        @order_details = OrderDetail.where(order_id: @order.id)
        @cart_items = current_customer.cart_items
        # @order_details = OrderDetail.where(order_id:@order.id)
        @sum = 0
        @order.order_details.each do |order_detail|
        @sum = @sum + (order_detail.item.price*1.08*order_detail.amount).round
        end
        @sum
        
    end

    def upddate
        
    end

    def destroy
    end

    def confirm
        @order = current_customer.orders.new
        @order_postal_code = params[:order][:postal_code]
        @cart_items = current_customer.cart_items
        @order_payment = params[:order][:payment_method]
        @address_option = params[:order][:address_option]
        # @status = params[:order][:payment_method]

        # if order_params[:payment_method] == '有効'
        #     @order.payment_method = true
        # elsif order_params[:payment_method] == '無効'
        #     @order.payment_method = false
        # end
        if @address_option == "0"
            @order_address = Order.new(address: current_customer.address,postal_code: current_customer.postal_code,name: current_customer.first_name + current_customer.last_name)
        elsif @address_option == "1"
            @address = Address.find(params[:order][:address_id])
            @order_address = Order.new(address: @address.address,postal_code: @address.postal_code,name: @address.name)
        elsif @address_option == "2"
            @order_address = Order.new(order_params)
        end
    end
    def count 
        
    end
    private
    def order_params
        params.require(:order).permit(:cart_item_id,:postal_code,:address,:name,:payment_method,:status,:shipping_cost,:total_payment)
      end
      def order_create_params
        params.require(:order).permit(:postal_code,:address,:name,:payment_method,:shipping_cost,:total_payment)
      end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def name
    @customer_fullname = first_name + last_name
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/views/customers/orders/complete.html.erb
<div class="thanks">
<center><h3>ご購入ありがとうございました！</h3></center>
</div>

app/views/customers/orders/confirm.html.erb
<h3>注文情報確認</h3>
    <%= form_with(model: @order, url:customers_orders_path,local: true, method: :post) do |f| %>  
    <div class="row">
        <div class="col-xs-8">
            <div class="left_box">
                <table border="2">
                    <tr style="background-color:lightgray">
                        <th>商品名</th><th>単価(税込)</th><th>数量</th><th>小計</th>
                    </tr>
                        <% sum = 0 %>
                        <% @cart_items.each do |cart_item|%>
                            <tr>
                                <td><%= cart_item.item.name %></td>
                                <td><%= (cart_item.item.price*$tax).round %></td>
                                <td><%= cart_item.amount %></td>
                                <td><%= (cart_item.item.price*1.08).round*(cart_item.amount) %></td>
                                    <% cart_item_price = (cart_item.item.price*1.08*cart_item.amount).round %>
                                        <% cart_item_price %>
                                        <% sum = sum + cart_item_price %>
                            </tr>
                        <% end%>
                </table> 
            </div>
        </div>
        <div class="col-xs-3">
            <div class="right_box">
                <table border="2">
                    <tr>
                        <td style="background-color:lightgray">送料</td>
                        <td>800</td>
                    </tr>
                    <tr>
                        <td style="background-color:lightgray">商品合計</td>
                        <td><%= sum.round.to_s(:delimited)  %></td>
                    </tr>
                    <tr>
                        <td style="background-color:lightgray">請求金額</td>
                        <td><%= (sum + 800).round .to_s(:delimited) %></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
            <div class="payment_address_box",style="margin-left:150px;">
                <div class="row">
                        <div class="col-xs-3">
                            <h5>支払い方法</h5>
                        </div>
                        <div class="col-xs-9">
                          <%= @order_payment %>
                        </div>
                </div>
                    <div class="row">
                        <div class="col-xs-3">
                            <h5>お届け先</h5>
                        </div>
                        <div class="col-xs-9">
                            <%= @order_address.postal_code%>
                            <%= @order_address.address%>
                            <br>
                            <%= @order_address.name%>
                        </div>
                    </div>
            </div>
          <%#addressオプションをローカルでエラーでたのでインスタンス変数にした%>
        
        <%= f.hidden_field :payment_method, value: @order_payment %>
        <%= f.hidden_field :postal_code, value: @order_address.postal_code %>
        <%= f.hidden_field :address, value: @order_address.address %>
        <%= f.hidden_field :name, value: @order_address.name %>
        <%= f.hidden_field :shipping_cost, value: 800 %>
        <%= f.hidden_field :total_payment, value: (sum + 800).round %>
        <%#= f.hidden_field :status, value: @status  %>
        <%#= f.hidden_field :status, value: true  %>
         <%#= form.submit '情報を確定する',customers_orders_complete_path,class:"btn btn-primary"%>
        <br>
        <center>
            <%= f.submit '情報を確定する',class:"btn btn-success"%>
        </center>
    <% end %>

app/views/customers/orders/index.html.erb
<div class="row">
<h3 >注文一覧履歴</h3>
 <table border="2">
    <tr style="background-color:lightgray">
      <th>注文日</th><th>配送先</th><th>注文商品</th><th>支払金額</th><th>ステータス</th><th>注文詳細</th>
    </tr>
    <tbody>
        <% @orders.each do |order|%>
                  <% amount_sum = 0%>
                    <td><%= order.created_at.strftime("%Y/%m/%d")%></td>
                    <td>
                        <%= order.postal_code  %>
                        <%= order.address %>
                        <%= order.customer.first_name + order.customer.last_name %>
                    </td>
                    <td>
                        <% order.order_details.each do |order_detail|  %>
                        <%= order_detail.item.name %>
                        <% end %>
                    </td>

                    <td><%= order.total_payment%></td>
                    <td><%= order.status %></td>
                    <td><%= link_to"表示する",customers_order_path(order),class:"btn btn-primary" %></td>
                </tr>
        <% end %>

    </tbody>

</table>

app/views/customers/orders/new.html.erb
    <h3>注文情報入力</h3>
   <div class="order_info">
    <%= form_with(model: @order,url:customers_orders_confirm_path,local: true, method: :get) do |form| %>
            <h2>支払方法</h2>
            <div class="payment">
                <%= form.radio_button :payment_method, :"クレジット" %>
                <%= form.label :payment_method,"クレジット",{style: "display: inline-block;"}%>
               <p> <%= form.radio_button :payment_method, :"銀行振込" %>
                <%= form.label :payment_method,"銀行振込",{style: "display: inline-block;"}%></p>
            </div>
            <h2>お届け先</h2>
        <div class="address">
            <div class="address_button">
                <%= form.radio_button :address_option, 0 %>
                <%= form.label :address_option,"ご自身の住所"%>
                <br>
                <%= form.label :address_option,""+(current_customer.address),{value: 0,style: "display: inline-block;"}%>
            </div>
            <div class="address_button">
                <%= form.radio_button :address_option, 1 %>
                <%= form.label :address_option,"登録住所から選択"%>
                <br>
            
                <%= form.collection_select :address_id, Address.where(customer_id:current_customer.id),:id,:address %>
            </div>
            <div class="address_button">
                <%= form.radio_button :address_option, 2 %>
                <%= form.label :address_option,"新しいお届け先",{value: 2,style: "display: inline-block;"}%>
            </div>
             <div class="row">
                <div class="col-xs-4">
                     <h4>郵便番号(ハイフンなし)</h4>
                </div>
                <div class="col-xs-8">  
                    <%= form.text_field :postal_code %>
                </div>
            </div>
            <div class="row"> 
                <div class="col-xs-4">
                    <h4>住所</h4>
                </div>
                <div class="col-xs-8">  
                    <%= form.text_field :address,:size=>"40" %>
                </div> 
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <h4>宛名</h4>
                </div>
                <div class="col-xs-8"> 
                    <%= form.text_field :name %>
                </div>
            </div>
      </div>
      <br>
      <%= form.submit "確認画面へ進む",class:"btn btn-primary",style:"margin-left:200px;"%>
    </div>
    <% end %>

app/views/customers/orders/show.html.erb
<div class="order_show_view">
<h3>注文履歴詳細</h3>
<div class="row">
        <div class="col-xs-7">
                 <table border="2">
                 <h4>注文情報</h4>
                    <tr>
                        <th style="background-color:lightgray">注文日</th>
                        <td><%= @order.created_at.strftime("%Y/%m/%d")%></td>
                    </tr>
                    <tr>
                        <th style="background-color:lightgray">配送先</th>
                        <td >
                            <%= @order.postal_code %><br>
                            <%= @order.address %><br>
                            <%= @order.name %>
                        </td>
                    </tr>
                    <tr>
                        <th style="background-color:lightgray">支払方法</th>
                        <td><%= @order.payment_method %></td>
                    </tr>
                    <tr>
                        <th style="background-color:lightgray">ステータス</th>
                        <td><%= @order.status %></td>
                    </tr>
            </table>
        </div>
        <div class="col-xs-5">
            <h4>請求情報</h4>
                    <table border="2">
                            <tr>
                                <th style="background-color:lightgray">商品合計</th>
                                <td><%= @sum.to_s(:delimited) %></td>
                            </tr>
                            <tr>
                                <th style="background-color:lightgray">送料</th>
                                <td>800</td>
                            </tr>
                            <tr>
                                <th style="background-color:lightgray">請求金額</th>
                                <td><%= (@sum + 800).to_s(:delimited) %></td>
                            </tr>
                    </table>
        </div>
</div>
    <h4>注文内容</h4>
       <table border="2">
            <%# sum = 0 %>
            <%# @cart_items.each do |cart_item|%>
                <thead>
                    <tr style="background-color:lightgray">
                    <th>商品名</th><th>単価(税込)</th><th>数量</th><th>小計</th>
                    </tr>
                </thead>
                <% @order_details.each do |order_detail| %>
                <tr>
                    <td><%= order_detail.item.name %></td>
                    <td><%= (order_detail.item.price*$tax).round %></td>
                    <td><%= order_detail.amount %></td>
                    <th>
                        <% one_item_sum = (order_detail.item.price*1.08).round*(order_detail.amount) %>
                        <%= one_item_sum.to_s(:delimited) %>
                    </th>

                </tr>
            <% end%>
        </table>
</div>