config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'customers/index'
  end
  namespace :admins do
    get 'genres/index'
  end
  get 'admins/top'
  get 'home/about'
  get 'customers/show'
  devise_for :customers, skip: :all

  root 'customers/items#index'

  namespace :customers  do
    resources :items, only:[:index,:show,:top]
    delete "cart_items/delete_all" => "cart_items#delete_all"
    get "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    get "customers_my_page" => "customers#show"
    # get "customers_edit" => "customers#edit"
    resource :customers, only:[:edit]
    patch "customers" => "customers#update"
    get "customers_unsubscribe" => "customers#unsubscribe"
    delete "customers_withdraw" => "customers#withdraw"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    resources :addresses, only:[:index,:new,:show,:edit,:update,:create,:destroy]
    resources :orders, only:[:new,:create,:index,:show,:update]
  end

    devise_for :customers, controllers: {sessions: "customers/sessions", registrations: 'customers/registrations', passwords: 'customers/passwords'}


    devise_scope :admin do
    devise_for :admins, controllers: {sessions: "admins/sessions", registrations: 'admins/registrations', passwords: 'admins/passwords'}
    # get "admins/sign_in" => "admins/sessions#new"
    # post "admins/sign_in" => "admins/sessions#create"
    # delete "admins/sign_out" => "admins/sessions#destroy"
  end

 
  namespace :admins  do
    resources :items, only:[:index,:new,:show,:edit,:update,:create]
    resources :genres, only:[:index,:edit,:create,:update]
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:edit,:update]
    resources :addresses
    get "admins" => "orders#count"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    validates :name,:postal_code,:address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    def delete_item(item)
        current_item = @items.find {|item| item.product == product }
        if current_item.decrement_quantity == 0
          @items.delete(current_item)
        end
        current_item
      end
      def sum
        @sum = [cart_item.item.price*1.08*(cart_item.amount)]+[cart_item.item.price*1.08*(cart_item.amount)]
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:cart_items,  dependent: :destroy
  has_many:orders,  dependent: :destroy
  has_many:addresses,  dependent: :destroy
  acts_as_paranoid
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items,  dependent: :destroy
    has_many :order_details,  dependent: :destroy
    belongs_to :genre
    attachment :image
    validates :is_active, inclusion: { in: [true, false]}

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: ["クレジット","銀行振込"]
    enum status: ["入金待ち","入金完了","製作中","発送準備中","発送済み"]
    validates :name, presence: true,
    length: { minimum: 1,maximum: 50}
    validates :postal_code, presence: true,
    length: { minimum: 1,maximum: 200}
    validates :address, presence: true,
    length: { minimum: 1,maximum: 200}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    enum making_status: ["着手不可","製作待ち","製作中","製作完了"]
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  def index
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to customers_my_page_path
    else
      render "index"
    end
    @addresses = current_customer.addresses
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end



  def destroy
    address = current_customer.address
    address.destroy
    redirect_to "index"
  end
  private
  def address_params
    params.require(:address).permit(:postal_code,:address,:name)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :null_session 
        helper_method :current_cart_item
        def after_sign_in_path_for(resource)
          case resource
          when Admin
            admins_admins_path
          when Customer
            root_path
          end
        end


    $tax = 1.08
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def about
    end
end

app/helpers/admins/addresses_helper.rb
module Admins::AddressesHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="about">
    <center>
    <h1>About</h1>
    <br>ながのCakeは全国発送可能なケーキ屋さんです。
    <br>お子様からお年寄りの方までお召し上がいただけるよう、
    <br>様々なバリエーションをご用意しております。
    <br>また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。
    <br>ぜひご注文ください。
    </center>
</div>

app/views/home/top.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>top</title>
</head>
<body>
    <div class="row">
        <div class="col-xs-3">
            <div class="genre_table">
                <table border="2">
                    <tr>
                        <th><h4>ジャンル検索<h2></th>
                    </tr>
                    <tr>
                        <th>ケーキ</th> 
                    </tr> 
                    <tr>
                        <th>焼き菓子</th> 
                    </tr> 
                    <tr>
                        <th>プリン</th> 
                    </tr>
                    <tr>
                        <th>キャンディ</th> 
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-xs-9">
                <div class="top_caption">
                    <br>ようこそ、Nagano cakeへ！
                    <br>このサイトはケーキ販売のECサイトになります。
                    <br>会員でない方も商品の閲覧ができますが、
                    <br>購入には会員登録が必要になります。
                </div>
                    <div class="recommend_item">
                        <h3>オススメ商品</h3>
                        <%#あとでEACH文入れるがいったん仮組み%>
                        <%#= attachment_image_tag @user,:profile_image, :fill, 60, 60, fallback: "noimage.jpg", size:'100x100' %>
                        <div class="items">
                            <%= link_to image_tag("1356_arena.jpg",:size => "150x70"), root_path %>
                            <p>商品名</p>
                            <p>金額</p>
                        </div>
                         <div class="items">
                            <%= link_to image_tag("1356_arena.jpg",:size => "150x70"),root_path %>
                            <p>商品名</p>
                            <p>金額</p>
                        </div>
                         <div class="items">
                            <%= link_to image_tag("1356_arena.jpg",:size => "150x70"), root_path %>
                            <p>商品名</p>
                            <p>金額</p>
                        </div>
                         <%= link_to "もっと見る",home_about_path %>
                    </div>
        </div>
</div>


</body>
</html>