config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'customers/index'
  end
  namespace :admins do
    get 'genres/index'
  end
  get 'admins/top'
  get 'home/about'
  get 'customers/show'
  devise_for :customers, skip: :all

  root 'customers/items#index'

  namespace :customers  do
    resources :items, only:[:index,:show,:top]
    delete "cart_items/delete_all" => "cart_items#delete_all"
    get "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    get "customers_my_page" => "customers#show"
    # get "customers_edit" => "customers#edit"
    resource :customers, only:[:edit]
    patch "customers" => "customers#update"
    get "customers_unsubscribe" => "customers#unsubscribe"
    delete "customers_withdraw" => "customers#withdraw"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    resources :addresses, only:[:index,:new,:show,:edit,:update,:create,:destroy]
    resources :orders, only:[:new,:create,:index,:show,:update]
  end

    devise_for :customers, controllers: {sessions: "customers/sessions", registrations: 'customers/registrations', passwords: 'customers/passwords'}


    devise_scope :admin do
    devise_for :admins, controllers: {sessions: "admins/sessions", registrations: 'admins/registrations', passwords: 'admins/passwords'}
    # get "admins/sign_in" => "admins/sessions#new"
    # post "admins/sign_in" => "admins/sessions#create"
    # delete "admins/sign_out" => "admins/sessions#destroy"
  end

 
  namespace :admins  do
    resources :items, only:[:index,:new,:show,:edit,:update,:create]
    resources :genres, only:[:index,:edit,:create,:update]
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:edit,:update]
    resources :addresses
    get "admins" => "orders#count"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    validates :name,:postal_code,:address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    def delete_item(item)
        current_item = @items.find {|item| item.product == product }
        if current_item.decrement_quantity == 0
          @items.delete(current_item)
        end
        current_item
      end
      def sum
        @sum = [cart_item.item.price*1.08*(cart_item.amount)]+[cart_item.item.price*1.08*(cart_item.amount)]
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:cart_items,  dependent: :destroy
  has_many:orders,  dependent: :destroy
  has_many:addresses,  dependent: :destroy
  acts_as_paranoid
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items,  dependent: :destroy
    has_many :order_details,  dependent: :destroy
    belongs_to :genre
    attachment :image
    validates :is_active, inclusion: { in: [true, false]}

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: ["クレジット","銀行振込"]
    enum status: ["入金待ち","入金完了","製作中","発送準備中","発送済み"]
    validates :name, presence: true,
    length: { minimum: 1,maximum: 50}
    validates :postal_code, presence: true,
    length: { minimum: 1,maximum: 200}
    validates :address, presence: true,
    length: { minimum: 1,maximum: 200}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    enum making_status: ["着手不可","製作待ち","製作中","製作完了"]
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  def index
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to customers_my_page_path
    else
      render "index"
    end
    @addresses = current_customer.addresses
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end



  def destroy
    address = current_customer.address
    address.destroy
    redirect_to "index"
  end
  private
  def address_params
    params.require(:address).permit(:postal_code,:address,:name)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    before_action :authenticate_admin!
    def index
        @items = Item.all

    end

    def edit
        @item = Item.find(params[:id])
        @genres = Genre.all
    end

    def create
        @item = Item.new(item_params)
        if item_params[:is_active] == '有効'
            @item.is_active = true
        elsif item_params[:is_active] == '無効'
            @item.is_active = false
        end

        if @item.save
            redirect_to admins_item_path(@item.id)
        else
            render new_admins_item_path
        end
    end

    def new
        @item = Item.new
        @genres = Genre.all
    end

    def show
        @item = Item.find(params[:id])
    end

    def update
        @genres = Genre.all
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to admins_item_path(@item)
          else
            render "index"
          end
    end
    private
    def item_params
        params.require(:item).permit(:name, :genre_id , :image, :introduction, :price, :is_active)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :null_session 
        helper_method :current_cart_item
        def after_sign_in_path_for(resource)
          case resource
          when Admin
            admins_admins_path
          when Customer
            root_path
          end
        end


    $tax = 1.08
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
    end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

    def index
        @items = Item.all
        @genres = Genre.all
    end
    def create

    end

    def new
    end

    def edit
    end

    def show
        @item = Item.find(params[:id])
        @cart_item = CartItem.new
        @genres = Genre.all
    end
    
    def upddate
    end

    def destroy
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def about
    end
end

app/helpers/admins/addresses_helper.rb
module Admins::AddressesHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/items/edit.html.erb
    <h3>商品詳細</h3>
            <%= form_with(model: @item, url:admins_item_path,method: :patch,local: true) do |f| %>
<div class="row">
        <div class="col-xs-4">
            <%= f.file_field :image_id %>
        </div>
        <div class="col-xs-7">
            <div class="row">
                <div class="col-xs-3">
                    <h4>商品名</h4>
                </div>
                <div class="col-xs-7">
                    <%= f.text_field :name %>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                <h4>商品説明</h4>
                </div>
                <div class="col-xs-7">
                    <%= f.text_field :introduction %>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <h4>ジャンル名</h4>
                </div>
                <div class="col-xs-7">
                    <%= f.collection_select(:genre_id, @genres, :id, :name ) %>
                </div>
           </div>
            <div class="row">
                <div class="col-xs-3">
                    <h4>税抜価格</h4>
                </div>
                <div class="col-xs-7">
                <%= f.text_field :price %>
                </div>
            </div>
                <div class="row">
                <div class="col-xs-3">
                    <h4>販売ステータス</h4>
                </div>
                <div class="col-xs-7">
                    <%= f.select :is_active,{'有効': true, '無効': false}, {include_blank: '選択してください'}, class:"col-xs-8",style:"backgroung-color:red;" %>
                    <%#= f.select :sex, {'男性': 1, '女性': 2}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
                </div>
            </div>
        </div>
</div>
            <%= f.submit"変更を保存",class:"btn btn-primary",style:"margin-left:800px;"%>
    <% end %>
    

app/views/admins/items/index.html.erb
<div class="row">
 <h3 style="background-color:gray;display:inline-block">商品一覧</h3>
      <%= link_to new_admins_item_path do %>
        <svg width="1em" height="5em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
      <% end %>
         <table class="table">
            <thead><tr><th>商品ID</th><th>商品名</th><th>税抜価格</th><th>ジャンル</th><th>ステータス</th></thead>
                  <% @items.each do |item|  %>
                    <tr>
                        <td><%=item.id %></td>
                        <td><%= link_to (item.name),admins_item_path(item) %></td>
                        <td><%=item.price %></td>
                        <td><%= item.genre.name %></td>
                        <td>
                          <% if item.is_active == YAML.load("true")%>
                            販売中
                          <% else  %>
                            販売停止中
                          <% end %>
                         </td>
                    </tr>
                  <% end %>
          </table>
</div>

app/views/admins/items/new.html.erb
<div class="row">
        <h3>商品新規登録</h3>
        <%= form_with(model: @item, url:admins_items_path,local: true,method: :post) do |f| %>
            <div class="col-xs-4">
              <%= f.attachment_field :image %>
            </div>
            <div class="col-xs-8">
                <h4>商品名</h4>
                    <%= f.text_field :name %>
                <h4>商品説明</h4>
                    <%= f.text_field :introduction %>
                <h4>ジャンル名</h4>
                    <%= f.collection_select(:genre_id, @genres, :id, :name ,prompt: "選択してください") %>
                <h4>税抜価格</h4>
                    <%= f.text_field :price %>
                <h4>販売ステータス</h4>
                    <%= f.select :is_active, ['有効', '無効'], {include_blank: 'ーー選択してくださいーー'}, class: 'sample' %>
              <br>
              <%= f.submit"新規登録",class:"btn btn-primary",style:"float:right;"%>
         </div>
    <% end %>
</div>

app/views/admins/items/show.html.erb
<h3>商品詳細</h3>
    <div class="row">
        <div class="col-xs-4">
            <td><%= attachment_image_tag @item,:image ,:fill,  60, 60, fallback: "noimage.jpg", size:'100x100'%></td>
        </div>
        <div class="col-xs-7">
            <div class="row">
                    <div class="col-xs-3">
                        商品名&nbsp;&nbsp;
                    </div>
                    <div class="col-xs-7">
                    <%= @item.name %>
                    </div>
            </div>
            <div class="row">
                    <div class="col-xs-3">
                        商品説明&nbsp;&nbsp;
                    </div>
                    <div class="col-xs-7">
                        <%= @item.introduction %>
                    </div>
            </div>
            <div class="row">
                    <div class="col-xs-3">
                        ジャンル名&nbsp;&nbsp;
                    </div>
                    <div class="col-xs-7">
                        <%= @item.genre.name %>
                    </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    税込価格(税抜価格)&nbsp;&nbsp;
                </div>
                <div class="col-xs-7">
                    <%= (@item.price * $tax).round  %>
                    (<%= @item.price %>)円
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    販売ステータス&nbsp;&nbsp;
                </div>
                <div class="col-xs-7">
                    <% if @item.is_active == YAML.load("true")%>
                            販売中
                            <% else  %>
                            停止
                            <% end %>
                </div>
            </div>
        </div>
</div>
        <%= link_to "編集する", edit_admins_item_path,class:"btn btn-primary",style:"float:right;" %>